### ISSUE TITLE
ios 上默认英文不好看

### ISSUE THREAD

**Issue by JetLua** [intellilab/vsort#1]
也许这样会更好。

``` css
* {
    font-family: "PingFang SC", "Heiti SC";
}
```

**Comment by JetLua** [comment]
截图为证。

![44419749775513197](https://cloud.githubusercontent.com/assets/6738986/26480546/18a9fe7a-420d-11e7-8ad0-d48377b80a0e.png)

**Comment by gera2ld** [comment]
又趁机炫耀了一把高贵的iPhone 7

**Comment by JetLua** [comment]
@gera2ld 你哪里看出是 iPhone 7 而不是 iPhone 8S
